name: Deploy NestJS App

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install SSH Key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          name: id_rsa
          known_hosts: ${{ secrets.EC2_HOST }}

      - name: Copy files to EC2
        run: |
          rsync -avz -e "ssh -o StrictHostKeyChecking=no" --exclude=node_modules . ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }}:~/app

      - name: Install dependencies and PM2, and restart application
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << 'EOF'
            sudo apt-get update
            sudo npm install -g pm2
            cd ~/app
            npm install
            npm run build
            pm2 restart all || pm2 start dist/main.js --name "nestjs-app"
          EOF

